project_id = "rhuchdexnbegaffkehhg"

[functions.create-organization]
verify_jwt = true

[functions.process-command]
verify_jwt = false

[functions.execute-decision]
verify_jwt = true

[functions.process-document]
verify_jwt = false
